// Auto-generated pinyin sort mapping
#let pinyin-sort(key) = {
  let map = (
    "AdaBoost": "ADABOOST",
    "AdaBoost算法": "ADABOOSTsuanfa",
    "Bagging": "BAGGING",
    "Boosting": "BOOSTING",
    "C4.5": "C4.5",
    "CART": "CART",
    "CART剪枝算法": "CARTjianzhisuanfa",
    "CART生成算法": "CARTshengchengsuanfa",
    "DBSCAN": "DBSCAN",
    "Gram矩阵": "GRAMjuzhen",
    "ID3": "ID3",
    "ID3算法生成决策树": "ID3suanfashengchengjueceshu",
    "ISOMAP": "ISOMAP",
    "K means聚类": "K MEANSjulei",
    "L1正则化": "L1zhengzehua",
    "L2正则化": "L2zhengzehua",
    "LASSO": "LASSO",
    "LLE": "LLE",
    "LVW（Las Vegas Wrapper）算法": "LVW（Las Vegas Wrapper）suanfa",
    "MDS": "MDS",
    "OOB 特征重要性计算 (MDA)": "OOB tezhengzhongyaoxingjisuan (MDA)",
    "Q-learning 算法 (异策略时序差分控制)": "Q-LEARNING suanfa (yicelveshixuchafenkongzhi)",
    "Relief": "RELIEF",
    "Relief 算法": "RELIEF suanfa",
    "SMO算法": "SMOsuanfa",
    "Sarsa 算法 (同策略时序差分控制)": "SARSA suanfa (tongcelveshixuchafenkongzhi)",
    "Sigmoid函数": "SIGMOIDhanshu",
    "Softmax": "SOFTMAX",
    "TSVM 算法": "TSVM suanfa",
    "VC维度": "VCweidu",
    "epsilon-贪心算法": "EPSILON-tanxinsuanfa",
    "k d树生成算法": "K Dshushengchengsuanfa",
    "k近邻法": "Kjinlinfa",
    "k近邻算法": "Kjinlinsuanfa",
    "主成分分析": "Zhuchengfenfenxi",
    "交叉熵": "Jiaochashang",
    "信息增益": "Xinxizengyi",
    "信息增益率": "Xinxizengyilv",
    "假设空间": "Jiashekongjian",
    "决策树": "Jueceshu",
    "几何间隔": "Jihejiange",
    "函数间隔": "Hanshujiange",
    "判别函数": "Panbiehanshu",
    "剪枝": "Jianzhi",
    "包裹式选择": "Baoguoshixuanze",
    "半朴素贝叶斯": "Banpusubeiyesi",
    "半监督学习": "Banjianduxuexi",
    "协同训练 (Co-training) 算法": "Xietongxunlian (Co-training) suanfa",
    "合页损失": "Heyesunshi",
    "吉布斯采样": "Jibusicaiyang",
    "同策略蒙特卡洛方法": "Tongcelvemengtekaluofangfa",
    "回归问题的提升树算法": "Huiguiwentidetishengshusuanfa",
    "基尼指数": "Jinizhishu",
    "多维缩放": "Duoweisuofang",
    "字典学习": "Zidianxuexi",
    "学习向量量化": "Xuexixianglianglianghua",
    "局部线性嵌入": "Jubuxianxingqianru",
    "岭回归": "Linghuigui",
    "嵌入式选择": "Qianrushixuanze",
    "广义瑞利商": "Guangyiruilishang",
    "广义线性回归": "Guangyixianxinghuigui",
    "度量学习": "Duliangxuexi",
    "异策略蒙特卡罗强化学习算法": "Yicelvemengtekaluoqianghuaxuexisuanfa",
    "弱分类器": "Ruofenleiqi",
    "强化学习": "Qianghuaxuexi",
    "感知机": "Ganzhiji",
    "感知机学习算法": "Ganzhijixuexisuanfa",
    "拉普拉斯修正": "Lapulasixiuzheng",
    "拉索回归": "Lasuohuigui",
    "损失函数": "Sunshihanshu",
    "支持向量": "Zhichixiangliang",
    "支持向量机": "Zhichixiangliangji",
    "无监督学习": "Wujianduxuexi",
    "最大熵模型": "Zuidashangmoxing",
    "最小二乘法": "Zuixiaoerchengfa",
    "朴素贝叶斯": "Pusubeiyesi",
    "朴素贝叶斯法": "Pusubeiyesifa",
    "机器学习": "Jiqixuexi",
    "条件独立性": "Tiaojiandulixing",
    "极大似然估计": "Jidashiranguji",
    "样本主成分分析：基于样本的奇异值分解": "Yangbenzhuchengfenfenxi：jiyuyangbendeqiyizhifenjie",
    "样本主成分分析：基于相关矩阵的特征值分解": "Yangbenzhuchengfenfenxi：jiyuxiangguanjuzhendetezhengzhifenjie",
    "样本主成分分析：基于（样本）协方差矩阵的特征值分解": "Yangbenzhuchengfenfenxi：jiyu（yangben）xiefangchajuzhendetezhengzhifenjie",
    "核函数": "Hehanshu",
    "梯度提升算法": "Tidutishengsuanfa",
    "泛化误差": "Fanhuawucha",
    "流形学习": "Liuxingxuexi",
    "熵": "Shang",
    "特征选择": "Tezhengxuanze",
    "生成式半监督高斯混合模型 EM 算法": "Shengchengshibanjiandugaosihunhemoxing EM suanfa",
    "监督学习": "Jianduxuexi",
    "直推学习": "Zhituixuexi",
    "矩阵补全": "Juzhenbuquan",
    "稀疏表示": "Xishubiaoshi",
    "策略迭代 (Policy Iteration)": "Celvediedai (Policy Iteration)",
    "类内散度矩阵": "Leineisandujuzhen",
    "类间散度矩阵": "Leijiansandujuzhen",
    "约束 k-means 算法": "Yueshu k-means suanfa",
    "约束种子 k-means 算法": "Yueshuzhongzi k-means suanfa",
    "线性判别分析": "Xianxingpanbiefenxi",
    "线性可分支持向量机": "Xianxingkefenzhichixiangliangji",
    "线性回归": "Xianxinghuigui",
    "线性支持向量机": "Xianxingzhichixiangliangji",
    "经验风险最小化": "Jingyanfengxianzuixiaohua",
    "结构风险最小化": "Jiegoufengxianzuixiaohua",
    "维数灾难": "Weishuzainan",
    "聚类": "Julei",
    "自助采样法": "Zizhucaiyangfa",
    "袋外样本": "Daiwaiyangben",
    "计算信息增益": "Jisuanxinxizengyi",
    "贝叶斯决策论": "Beiyesijuecelun",
    "贝叶斯网络": "Beiyesiwangluo",
    "过拟合": "Guonihe",
    "过滤式选择": "Guolvshixuanze",
    "近邻成分分析": "Jinlinchengfenfenxi",
    "近邻成分分析（NCA）": "Jinlinchengfenfenxi（NCA）",
    "迭代式逆强化学习算法 (Iterative IRL)": "Diedaishiniqianghuaxuexisuanfa (Iterative IRL)",
    "逻辑斯蒂回归": "Luojisidihuigui",
    "逻辑斯蒂回归模型": "Luojisidihuiguimoxing",
    "间隔最大化": "Jiangezuidahua",
    "随机梯度下降": "Suijitiduxiajiang",
    "随机森林": "Suijisenlin",
    "随机森林算法": "Suijisenlinsuanfa",
    "集成学习": "Jichengxuexi",
    "非线性支持向量机学习算法": "Feixianxingzhichixiangliangjixuexisuanfa",
    "马尔可夫决策过程": "Maerkefujueceguocheng",
    "马氏距离": "Mashijuli",
    "高斯混合聚类": "Gaosihunhejulei",
  )
  map.at(key, default: key)
}